# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 764399d8c5c94f3c1019a678a07d265257154d90932755d8687c2b7a143698c0f792502823e70fbb34f55579cf29671ea8c362af2e1a7804b3194df996634218

test:
  secret_key_base: 5b1e343a08bbd60d0f0b69525ef6e9091eaf8884f3d36e3d0cc2204828b62c867a55817a0bba56e37e3de3ca4f9297f7f1bb2b0870dedd4864292ce83f95ec6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
